version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  deploy-docker:
    docker:
      - image: node:12
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/install
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.4"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and Publish Image
          command: ./docker.sh
  deploy-terraform:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: cd terraform
      - run: terraform plan
      - run: terraform apply -auto-approve
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker
      - deploy-terraform:
          requires:
            - deploy-docker