version: 2.1
jobs:
  deploy-docker:
    docker:
      - image: node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            export PATH=$PATH:/root/.local/bin
            apt-get -y -qq update
            apt-get -y -qq install python3
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.4"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and Publish Image
          command: |
            # PATH isn't saved from step to step
            export PATH=$PATH:/root/.local/bin
            ./docker.sh
  deploy-terraform:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: 
          name: Run terraform
          command: |
            cd terraform
            terraform plan
            terraform apply -auto-approve
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker
      - deploy-terraform:
          requires:
            - deploy-docker