version: 2
jobs:
  deploy-docker:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: ./docker.sh
  deploy-terraform:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: cd terraform
      - run: terraform plan
      - run: terraform apply
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker
      - deploy-terraform:
        requires:
          - deploy-docker